### ISSUE TITLE
Zoom and action boxes not at right position when screen ratio != pdf ratio

### ISSUE THREAD

**Issue by thamnos** [TrilbyWhite/Slider#21]
When looking at a 4:3 pdf on a 16:9 screen, the pdf content is positioned correctly in the middle of the screen. However, boxes around links and the regions that are zoomed are misplaced: On the left of the screen, they are too far left and on the right they are too far right. I believe that this happens because these coordinates are not scaled appropriately.

**Comment by TrilbyWhite** [comment]
I've just moved version 4 to the master branch - and zooming works completely differently.  So this issue is only relevant to the v3 branch which I don't intend to update further - though you can feel free to submit pull requests or patches for v3 if that is of value to you.
