### ISSUE TITLE
sorter is lagging/ updating slowly

### ISSUE THREAD

**Issue by vitamins** [TrilbyWhite/Slider#25]
In the sorter, the highlighted slide is following the mouse cursor with a distinct lag.
Ideally the highlighted slide would always be the one under the mouse cursor.
Looks like a game where the AI player has to catch the mouse.

**Comment by TrilbyWhite** [comment]
You're right.  I never experienced this before - but I am seeing it now (and no slider code has changed - though poppler and cairo have had updates).

While this is definitely a bug, I'm not sure if I'll find time to work on it as I'm focusing on getting version 4 up and running (see the v4 branch of this repo).  If v4 doesn't make progress as planned, I'll patch up v3, but for now I'd rather get the new one up and running.  Version 4 takes a completely different approach to the slide sorter.

**Comment by TrilbyWhite** [comment]
I'll close this as 'won't fix' as I just pushed version 4 to 'master'.  Version 4 is not complete, but it is mostly functional (except for one of the main uses of multimonitor presentations - this is coming soon).
