### ISSUE TITLE
error: ignoring return value of ‘chdir’

### ISSUE THREAD

**Issue by The-Compiler** [TrilbyWhite/Slider#27]
Trying to build this on an up-to-date Archlinux gives me this as the default `CFLAGS` include `-Werror`:

```
src/config.c: In function ‘config_init’:
src/config.c:86:3: error: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Werror=unused-result]
   chdir(dir); chdir(STRING(PROGRAM_NAME));
   ^
src/config.c:86:15: error: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Werror=unused-result]
   chdir(dir); chdir(STRING(PROGRAM_NAME));
               ^
src/config.c:90:3: error: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Werror=unused-result]
   chdir(dir); chdir(".config"); chdir(STRING(PROGRAM_NAME));
   ^
src/config.c:90:15: error: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Werror=unused-result]
   chdir(dir); chdir(".config"); chdir(STRING(PROGRAM_NAME));
               ^
src/config.c:90:33: error: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Werror=unused-result]
   chdir(dir); chdir(".config"); chdir(STRING(PROGRAM_NAME));
                                 ^
src/config.c:95:2: error: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Werror=unused-result]
  chdir(old_dir);
  ^
cc1: all warnings being treated as errors
<builtin>: recipe for target 'config.o' failed
make: *** [config.o] Error 1
make: *** Waiting for unfinished jobs....
src/links.c: In function ‘_spawn’:
src/links.c:154:2: error: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Werror=unused-result]
  system(line); // TODO
  ^
cc1: all warnings being treated as errors
<builtin>: recipe for target 'links.o' failed
make: *** [links.o] Error 1
```

**Comment by TrilbyWhite** [comment]
Thanks for the report.  I'm not an expert on compiler flags, but -Werror is often too conservative and it is not the default for makepkg.  I could set an override to make sure it is *not* set, but I'd prefer not to.

Slider builds fine here with makepkg defaults.

But also note that with the current git head I've been trying some new things - and at least in my own recent tests I've not been pleased with the results.  I may revert back to X11 rather than SFML and/or drastically change some of the inner workings as soon as I get some time to work on it again.

The v3 branch should still work well though.

**Comment by The-Compiler** [comment]
It seems it works with `makepkg` because it *does* override `CFLAGS`. I tried building it via `make` (as I just wanted to give it a quick try without installing it), and that happens because you [set `-Werror` in your Makefile](https://github.com/TrilbyWhite/Slider/blob/master/Makefile#L15). :wink:

Glad to hear you're happy with qutebrowser!

**Comment by TrilbyWhite** [comment]
Doh.  What the heck was that.  I must have added that line at some point for testing and forgot to remove it.  Thanks, I just removed the offending line from the Makefile.
